"""empty message

Revision ID: ecc74b94083e
Revises: dfd56fe1b05f
Create Date: 2019-03-13 12:17:50.932685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc74b94083e'
down_revision = 'dfd56fe1b05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('post', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_time_stamp'), 'post', ['time_stamp'], unique=False)
    op.drop_index('ix_post_time_stamp', table_name='post')
    #op.drop_column('post', 'time_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('time_stamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_post_time_stamp', 'post', ['time_stamp'], unique=False)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
